name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  angular2: ^3.0.0
  angular_built_redux:
    path: ../.

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2
  test: ^0.12.0
  built_collection: ^1.3.0
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0

dependency_overrides:
  built_redux:
    path: ../../built_redux/.

transformers:
- angular_built_redux
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
